#!/bin/bash
# ==================================================================
# FILE     runRegressionTest
# MACHINE  all
# INFO     
#
# DATE     18.10.2022
# OWNER    Bischofberger
# ==================================================================

SOURCEDIR="$HOME/Documents/Work/BMS-ZH/01-Unterricht/12-Projekte/randgentftest"
TESTDIR="testfiles"

PKGFILES=("randgentftest.lua" "randgentftest.sty" "randgentftestbmzcls.cls")


die(){
	echo -e "$0: Error: $1" >&2
	exit 1
}


prepare(){
  echo -n "copying pkgfiles... "
  for pkgfile in "${PKGFILES[@]}" ; do
    cp -f "$SOURCEDIR/$pkgfile" "$SOURCEDIR/$TESTDIR/$pkgfile"
  done
  echo -e "done\n\n"
}


clean(){
  echo -n -e "\n\ndeleting pkgfiles... "
  for pkgfile in "${PKGFILES[@]}" ; do
    rm -f "$SOURCEDIR/$TESTDIR/$pkgfile"
  done
  echo -e "done"
}


prepare
cd "$SOURCEDIR/$TESTDIR"

# if no argument is given, compile all files in folder
if [ -z "$1" ] ; then
  latexmk -lualatex -interaction=nonstopmode -file-line-error
fi

# if first argument is a file, treat all following arguments as potential files
if [ -f "$1" ] ; then
  for file in "$@" ; do
    latexmk -lualatex -interaction=nonstopmode -file-line-error "$file"
  done
else
  die "error: given argument is not a file"
fi

clean
